child/urls.py
from unicodedata import name
from django.urls import path
from . import views


from .views import (

AddChildview,
ChildListView,
ChildDetailedView,
AddTestview
	 )




urlpatterns = [    

  

   path('children',ChildListView.as_view(),name="child-list"),
   path('add_child/<int:pk>/',AddChildview.as_view(),name="add-child"),
    path('add_child_test/<childregno>/',AddTestview.as_view(),name="add-test"),
   path('child_detail/<int:pk>',ChildDetailedView.as_view(),name="child-detail"),
  # path('patients/addmedicalrecord/<int:pk>/',AddMedcialRecordView.as_view(),name="add-medical-record"),

  path('searchedchild',views.search_child,name="searched-child")


  
   
  
]

main/urls.py
from django.urls import path
from . import views



urlpatterns = [    

  
   path('dashboard/',views.dashboard, name ='dashboard'),


  
 
  
]

neonatal/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('patients.urls')),  
    path('',include('users.urls')),  
    path('',include('main.urls')), 
    path('',include('child.urls')), 
	path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='login'), name='logout'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

child/models.py
from random import random
from django.db import models
from twilio.rest import Client
from patients.models import patient
from datetime import datetime,timedelta
from django.contrib.auth.models import User 
from django.core.validators import  MaxValueValidator,MinValueValidator
import random


#Create your models here.https://medlineplus.gov/ency/article/003402.htm
#https://my.clevelandclinic.org/health/diseases/9685-stillbirth
#https://americanpregnancy.org/healthy-pregnancy/labor-and-birth/apgar-test/

def childregid():
     return str(random.randint( 100,9999))

class child(models.Model):
     score = [MaxValueValidator(2),MinValueValidator(0)]
     motherid = models.ForeignKey(patient,on_delete=models.CASCADE)
     childregno = models.IntegerField(default=childregid)
     heartrate = models.IntegerField(default='',validators =[MaxValueValidator(2),MinValueValidator(1)] )
     muscletone = models.IntegerField(default='',validators =score)
     skincolour = models.IntegerField(default='',validators =score)
     reflex = models.IntegerField(default='',validators =score)
     Breathing = models.IntegerField(default='',validators =score)
     agparscore = models.IntegerField(default=0,validators=[MaxValueValidator(10),MinValueValidator(0)])
     Dob = models.DateTimeField()
     nurseincharge = models.ForeignKey(User,on_delete=models.CASCADE)

     def __str__(self):
            return f'{ self.motherid.patient_name } child'
     
     #  #save method
     def save(self, *args, **kwargs):
        #if heartrate is less than 1 
        if self.heartrate < 2:
            #twilio code
            account_sid = 'AC786ed08d13a127ed6c6567f38533a55f'
            auth_token = 'eef515624c10273f2b57ed8718e81e81'
           # auth_token = '569149322e781ebd23f1c97d7d9936a0'
            client = Client(account_sid, auth_token)

            message = client.messages.create(
                           messaging_service_sid='MG43fefeae27269bdadf328bb970ede776',
                           body=f'New Born Child with regno  {self.childregno}. Has a heartrate of 1 Please monitor the baby',
                           from_='+19896834626',
                           to='+263777459622' 
                                    )

            print(message.sid)
     ##    return super().save(*args, **kwargs)

 


class childtest(models.Model):
     score = [MaxValueValidator(2),MinValueValidator(0)]
     child_regno = models.IntegerField(default='')
     heart_rate = models.IntegerField(default='',validators =[MaxValueValidator(2),MinValueValidator(1)] )
     muscle_tone = models.IntegerField(default='',validators =score)
     skin_colour = models.IntegerField(default='',validators =score)
     re_flex = models.IntegerField(default='',validators =score)
     Brea_thing = models.IntegerField(default='',validators =score)
     agpar_score = models.IntegerField(default=0,validators=[MaxValueValidator(10),MinValueValidator(0)])


     def __str__(self):
          return f'{self.child_regno}'
     
     #    #save method
     def save(self, *args, **kwargs):
        #if heartrate is less than 1 
        if self.heart_rate < 2:
            #twilio code
            account_sid = 'AC786ed08d13a127ed6c6567f38533a55f'
            auth_token = 'eef515624c10273f2b57ed8718e81e81'
           # auth_token = '569149322e781ebd23f1c97d7d9936a0'
            client = Client(account_sid, auth_token)

            message = client.messages.create(
                           messaging_service_sid='MG43fefeae27269bdadf328bb970ede776',
                           body=f'New Born Child with regno  {self.child_regno}. Has a heartrate of 1 Please monitor the baby',
                          from_='+19896834626',
                           to='+263777459622' 
                                    )

            print(message.sid)
        return super().save(*args, **kwargs)


# def deadchildid():
#      return str(random.randint( 11111,30253))
# class deadchild(models.Model):
#       motherid = models.ForeignKey(patient,on_delete=models.CASCADE)
#       deadchildregno = models.IntegerField(default=deadchildid)
     
    

child/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q ,Count
from django.views.generic import (

ListView,
DetailView,
FormView,
UpdateView ,
DeleteView,CreateView
)

from .models import child 
from patients.models import *
from main.forms import *
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from sendsms.message import SmsMessage
from django.conf import settings

class ChildListView(LoginRequiredMixin, ListView):
    model = child
    template_name = 'child/childlist.html'
    context_object_name = 'children'

    def get_context_data(self,**kwargs):
        context = super(ChildListView, self).get_context_data(**kwargs)
        queryset = child.objects.values('motherid').annotate(count=Count('motherid')).order_by('motherid')
        context['count'] = queryset
        return context

class ChildDetailedView(LoginRequiredMixin,DetailView):
    model = child
    template_name = 'child/child-detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['othertest'] = childtest.objects.filter(child_regno = self.object.childregno)
        ctx['xyz'] = child.objects.values('agparscore').annotate(count=Count('agparscore'))
        ctx['abc'] = childtest.objects.values('agpar_score').annotate(count=Count('agpar_score'))
        ctx['agpar_score_count'] =childtest.objects.filter(Q(child_regno = self.object.childregno) & Q( agpar_score__gte=7)).count()
        ctx['agparscore_count'] =child.objects.filter(Q(childregno = self.object.childregno) & Q( agparscore__gte=7)).count()
        ctx['heart_rate_count'] =childtest.objects.filter(Q(child_regno = self.object.childregno) & Q( heart_rate__gte=1)).count()
        ctx['heartrate_count'] =child.objects.filter(Q(childregno = self.object.childregno) & Q( heartrate__gte=1)).count()
        ctx['agpar_result'] = (ctx['agpar_score_count'] + ctx['agparscore_count'])
        ctx['heart_rate_result'] = (ctx['heart_rate_count'] + ctx['heartrate_count'])
        return ctx

class AddChildview(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    model = child
    form_class = Addchildform
    template_name = 'child/addchild.html'
    success_url = reverse_lazy('patients')
    success_message = 'child Added Successfully'

    def get_context_data(self, **kwargs):
        ctx =  super().get_context_data(**kwargs)
        ctx['motherinfo'] = patient.objects.get(id=self.kwargs['pk'])
        return ctx

    def form_valid(self,form):
        motherid = patient.objects.get(id=self.kwargs['pk'])    
        form.instance.motherid = motherid
        form.instance.nurseincharge = self.request.user
        return super().form_valid(form)

class  AddTestview(LoginRequiredMixin, SuccessMessageMixin,CreateView):
    model = childtest
    form_class = Addchildtestform
    template_name = 'child/addchildtest.html'
    success_url = reverse_lazy('child-list')

    def get_context_data(self, **kwargs):
        ctx =  super().get_context_data(**kwargs)
        ctx['childregno'] = child.objects.get(childregno=self.kwargs['childregno'])
        return ctx
    

    def form_valid(self,form):
        child_regno = child.objects.get(childregno =self.kwargs['childregno'])    
        form.instance.child_regno = child_regno.childregno
        return super().form_valid(form)


@login_required
def search_child(request):
	if request.method == 'POST':
		searchedchild = request.POST.get('searchedchild')
		children = child.objects.filter(
			Q(childregno__contains = searchedchild)
		

			)
		return render(request,'child/childlist.html',{'children':children})
	else:
		return render(request,'child/childlist.html')

child/templates/child/addchild.html
{% extends "main/header.html "%}
{% load static  %}
{% load crispy_forms_tags %}
{% block content%}
 
<br><br>
<h2>Add  Child of {{ motherinfo.patient_name }} {{ motherinfo.patient_surname }}</h2>



  

 <form method="POST" enctype="multipart/form-data" autocomplete="off">
       {% csrf_token %}
     <div class="container">
  <div class="row">
    <div class="col">
      {{ form|crispy }}

    <!-- <input type="text" id="apgar"/> -->
      <button type="submit" class="btn btn-info">
        Submit
       
       </button>
        <a href="{% url 'child-list' %}"><button class="btn btn-danger">
        Dead Child
       
       </button></a>
    </div>
    <div class="col">
    
    
    </div>
  
  </div>
</div>
<hr/>
<script src="{% static 'main/js/jquery.js' %}"></script>  



<script>
  $("input").on("input", function() {
    var ret = parseInt($("#id_heartrate").val()) + parseInt($("#id_muscletone").val() )
      + parseInt($("#id_skincolour").val() )
      + parseInt($("#id_reflex").val() ) 
     + parseInt($("#id_Breathing").val() ) 
    //   + parseInt($("#id_muscletone").val() )

    $("#apgar").val(ret);
    $("#id_agparscore").val(ret);
  });

  
 
  
</script>


{% endblock content %}


  
 
  
</script>

child/templates/child/addchildtest.html
{% extends "main/header.html "%}
{% load static  %}
{% load crispy_forms_tags %}
{% block content%}
 
<br><br>
<h3>Add  Agpare score Test for child with id  {{ childregno.childregno }}</h3>



  

 <form method="POST" enctype="multipart/form-data" autocomplete="off">
       {% csrf_token %}
     <div class="container">
  <div class="row">
    <div class="col">
      {{ form|crispy }}

   
      <button type="submit" class="btn btn-info">
        Submit
       
       </button>
    </div>
    <div class="col">
    
    
    </div>
  
  </div>
</div>
<hr/>
<script src="{% static 'main/js/jquery.js' %}"></script>  



<script>
  $("input").on("input", function() {
    var ret = parseInt($("#id_heart_rate").val()) + parseInt($("#id_muscle_tone").val() )
      + parseInt($("#id_skin_colour").val() )
      + parseInt($("#id_re_flex").val() ) 
     + parseInt($("#id_Brea_thing").val() ) 


    $("#apgar").val(ret);
    $("#id_agpar_score").val(ret);
  });

  
 
  
</script>


{% endblock content %}


  
 
  
</script>

child/templates/child/child-detail.html
{% extends "main/header.html "%}
{% load static  %}
{% load mathfilters %}
{% block content%}
<style>
      #childdetail{

   background: url('{% static "main8/images/neo.png" %}');
  
  background-repeat: no-repeat;
  background-size: cover; 
  
  
 
} 
#childtable{
    background-color: white;
    opacity: 0.9;
    color: black;
}
</style>
<br/><br/>
<h5>Child birth number {{ object.childregno }}</h5>
<h5>Mother - {{ object.motherid.patient_surname }}</h5>
<a class="dropdown-item" href="{% url 'add-test' object.childregno %} ">Add Test </a>
<br/>

<div class="container bootstrap snippets bootdey">
   
        <div class="post-list">
            <div class="row">
                <div class="col-sm-2">
                  
                    <div class="picture">
                        <img alt="Child" src="{% static 'main/images/neo.png' %}">
                    </div>
                </div>
            
                <div class="table-responsive" id="childdetail">
                    <table class="table table-hover" id="childtable">
                        <thead>

                            <tr>
                            
                              <th scope="col">Heart Rate</th>
                              <th scope="col">Skin Colour</th>
                              <th scope="col">Reflex</th>
                              <th scope="col">Breathing</th>
                              <th scope="col">Muscle Tone</th>
                             <th scope="col">AgPar Score</th>
                             <th scope="col">prediction</th>
                             <!-- <th scope="col">Action</th> -->
                            </tr>
                            </thead>
                            <tbody>
                              
                                <tr>
                         

                                  <th scope="row">{{  object.heartrate}}</th>
                                  <th scope="row">{{  object.skincolour}}</th>
                                  <th scope="row">{{  object.reflex}}</th>
                                  <th scope="row">{{  object.Breathing }}</th>
                                  <th scope="row">{{  object.muscletone}}</th>
                                  <th scope="row"> {{ object.agparscore }}</th>
                                  <th scope="row">
                                        
                                        {% if object.heartrate < 1 %}
                                            dead

                                            {% else %}
                                      
                                            
                                        
                                        {% if object.agparscore < 7 and object.heartrate <= 1 %}
                                            The child need more atention since the heart is <br/> not perfoming very well.
                                            the child has {{ object.heartrate|div:2|mul:100 }}% of surviving.

                                            <p class="text-muted"><span class="f-left">{{ object.heartrate|div:2|mul:100 }}%</span></p>
                                            <div class="progress"><div class="progress-bar bg-c-red" style="width: {{ object.heartrate|div:2|mul:100 }}%"></div></div>
                                       
                                         {% elif  object.agparscore < 7 and object.heartrate > 1 %}

                                         The child is well since the heart is  perfoming very well.
                                         the child has {{ object.heartrate|div:2|mul:100 }}% of surviving.
                                         look in the other factors for a health baby.
                                         <p class="text-muted"><span class="f-left">{{ object.heartrate|div:2|mul:100 }}%</span></p>
                                         <div class="progress"><div class="progress-bar bg-c-green" style="width: {{ object.heartrate|div:2|mul:100 }}%"></div></div>
                                         {% elif object.agparscore > 6 and object.heartrate < 2 %}
                                         The child need more atention since the heart is <br/> not perfoming very well.
                                         the child has {{ object.heartrate|div:2|mul:100 }}% of surviving.

                                         <p class="text-muted"><span class="f-left">{{ object.heartrate|div:2|mul:100 }}%</span></p>
                                         <div class="progress"><div class="progress-bar bg-c-red" style="width: {{ object.heartrate|div:2|mul:100 }}%"></div></div>
                                            {% endif %}
                                            
                                            {% endif %}

                                  </th>
                                
                                 
                                  
                                  <!-- <td><div class="btn-group dropleft">
                                <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Action
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                
                                <a class="dropdown-item" href="{% url 'add-test' object.childregno %} ">Add test 2</a>
                                
                                
                                </div>
                                </div></td> -->
                                </tr>

                                {% for a  in othertest  %}
                                <tr>
                                 
                                    <th scope="row">   {{ a.heart_rate }}</th>
                                    <th scope="row">   {{ a.skin_colour }}</th>
                                    <th scope="row">   {{ a.re_flex }}</th>
                                    <th scope="row">   {{ a.Brea_thing }}</th>
                                    <th scope="row">   {{ a.muscle_tone }}</th>
                                    <th scope="row">   {{ a.agpar_score }}</th>
                                    <th scope="row">   

                                        {% if a.agpar_score < 7 and a.heart_rate <= 1 %}
                                            
                                        The child need more atention since the heart is <br/> not perfoming very well.
                                        The child has {{ object.heartrate|div:2|mul:100 }}% of surviving
                                        <p class="text-muted"><span class="f-left">{{ object.heartrate|div:2|mul:100 }}%</span></p>
                                            <div class="progress"><div class="progress-bar bg-c-red" style="width: {{ object.heartrate|div:2|mul:100 }}%"></div></div>
                                       
                                   
                                     {% elif  a.agpar_score < 7 and a.heart_rate > 1 %}


                                     The child is well since the heart is  perfoming very well.
                                     The child has {{ a.heart_rate|div:2|mul:100 }}% of surviving.
                                     look in the other factors for a health baby.
                                     <p class="text-muted"><span class="f-left">{{ a.heart_rate|div:2|mul:100 }}%</span></p>
                                            <div class="progress">
                                            <div class="progress-bar bg-c-green" style=" width: {{ a.heart_rate|div:2|mul:100 }}% "></div>
                                            </div>

                                     {% elif a.agpar_score > 7 and a.heart_rate < 1 %}
                                            ma1
                                    {% elif a.agpar_score > 7 and a.heart_rate > 1 %}
                                            The baby is fit and very very fine and <br/> have a {{ a.heart_rate|div:2|mul:100 }}%
                                            chance of surviving.
                                            <p class="text-muted"><span class="f-left">{{ a.heart_rate|div:2|mul:100 }}%</span></p>
                                            <div class="progress">
                                            <div class="progress-bar bg-c-green" style=" width: {{ a.heart_rate|div:2|mul:100 }}% "></div>
                                            </div>

                                    {% elif a.heart_rate == 0 %}
                                    dead
                                    {% endif %}
                                    </th>
                                 
                                    <!-- <th><div class="btn-group dropleft">
                                        <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Action
                                        </button>
                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        
                                        <a class="dropdown-item" href="{% url 'add-test' object.childregno %} ">Add test 2</a> -->
                                        <!-- <a class="dropdown-item" href=" url 'object-update' object.id ">Update</a>
                                        <a class="dropdown-item" href=" url 'delete-object' object.id  ">Delete</a>
                                        
                                        
                                        </div>
                                        </div>
                                    </th> -->
                                
                                </tr>
                               
                                </tbody>
                                
                                {% endfor %}
                      </table> 
                    

                </div>
               
            </div>
        </div>
<!-- {{ agpar_score_count }} | 
{{ agparscore_count }} -->
<hr>
<!-- {{ heart_rate_count }}
{{ heartrate_count }}
.....
{{ xyz }} -->

    
  
  
</div>

{% endblock content %}

child/templates/child/childlist.html
{% extends "main/header.html "%}
{% load static  %}
{% block content%}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h2 class="h3">All Infants

     
   </h2>


  </div>
  {% include "main/messages.html" %}


  <form class="form-inline my-6 my-lg-6" method="Post"  action="{%  url 'searched-child' %}">
    {% csrf_token %}
     <input class="form-control mr-sm-2" name="searchedchild" required="required" type="text" placeholder="Search" aria-label="Search">
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   
   </form>

<table class="table table-hover">
<thead class="thead-dark">

<tr>
   <th scope="col">Child id</th>
   <th scope="col">Mother of child</th>
 <th scope="col">D.O.B</th> 
 <th scope="col">Action</th>
</tr>
</thead>
<tbody>
{% for child in children %}
<tr>
<th scope="row">{{  child.childregno}} </th>
<th>{{  child.motherid.patient_name}} {{  child.motherid.patient_surname}}</th>
   <th scope="row"> {{ child.Dob|date:"d M Y " }}</th> 

 
  
  <td><div class="btn-group dropleft">
<button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Action
</button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

<a class="dropdown-item" href="{% url 'child-detail' child.id %}">View</a>



</div>
</div></td>
</tr>

</tbody>

{% endfor %}
</table>
<nav aria-label="Page navigation example">
<nav aria-label="Page navigation example">
<ul class="pagination justify-content-center">
{% if is_paginated %}

  {% if page_obj.has_previous %}
   <li class="page-item disabled"> <a class="btn btn-outline-secondary mb-4"  href="?page=1">First </a></li>
   <li class="page-item disabled"> <a class="btn btn-outline-secondary mb-4"  href="?page={{ page_obj.previous_page_number}}">Previous </a></li>
  {% endif %}

  {%  for num in page_obj.paginator.page_range  %}

    {% if page_obj.number == num %}

    <li class="page-item disabled">  <a class="btn btn-outline-info mb-4"  href="?page={{ num }}">{{ num }} </a></li>

    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}

        <li class="page-item disabled"> <a class="btn btn-outline-info mb-4"  href="?page={{ num }}">{{ num }} </a></li>
     {% endif %}

    {% endfor%}

{% if page_obj.has_next %}
 <li class="page-item disabled">   <a class="btn btn-outline-info mb-4"  href="?page={{ page_obj.next_page_number }}">Next </a></li>
     <li class="page-item disabled">   <a class="btn btn-outline-info mb-4"  href="?page={{ page_obj.paginator.num_pages }}">Last </a></li>
  {% endif %}
  {% endif %}



</ul>
</nav>






    
{% endblock content %}
    