main/urls.py
from django.urls import path
from . import views



urlpatterns = [    

  
   path('dashboard/',views.dashboard, name ='dashboard'),


  
 
  
]

neonatal/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('',include('patients.urls')),  
    path('',include('users.urls')),  
    path('',include('main.urls')), 
    path('',include('child.urls')), 
	path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(next_page='login'), name='logout'),
 
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

patients/urls.py
from django.urls import path

from patients.models import patient
from . import views


from .views import (



   UpdatepatientView,
   patientslistview,
   patientdetail,
   AddPatientView,
   DeletePatientView,
   AddMedcialRecordView,
   AssignNurseView,
   ViewChildrenView,

	 )




urlpatterns = [    

  


   path('patients/',patientslistview.as_view(),name="patients"),
   path('patientdetail/<int:pk>',patientdetail.as_view(),name="patient-detail"),
   path('patient/addpatients/',AddPatientView.as_view(),name="add-patient"),
   path('patient/delete/<int:pk>',DeletePatientView.as_view(),name="delete-patient"),
   path('patient/update/<int:pk>/', UpdatepatientView.as_view(),name="patient-update"),

   path('htmx/patientdetail/<pk>/delete/', views.delete_medical_record, name="delete-medical-record"),
   path('patient/addmedicalrecord/<int:pk>/',AddMedcialRecordView.as_view(),name="add-medical-record"), 

   path('patient_children/<int:pk>',ViewChildrenView.as_view(),name="view-children"),

   path('assignurset/<int:pk>/',views.assignurset,name="assignurset"),
   path('assign/<int:pk>/',views.AssignNurseView,name="assign-nurse"),

   path('export_csv/',views.export_csv,name="export-csv"),
   path('export_pdf/',views.export_pdf,name="export-pdf"),

  
   
  
]

patients/models.py
from ast import Assign
from pickle import TRUE
from django.db import models
from django.contrib.auth.models import User 
# from django.utils import timezone
from datetime import datetime ,timedelta
from django.core.validators import  MaxValueValidator,MinValueValidator
from neonatal.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib import messages
# from django.urls import reverse
# User._meta.get_field('email').verbose_name = "new name"

class patient(models.Model):
    blood_type=(
        ("A"," A "),
        ("B","B"),
        ("C","C"),
    )
    patient_name = models.CharField(max_length=100)
    patient_surname = models.CharField(max_length=100,blank=True)
    patient_nid = models.CharField(max_length=20,default='',unique=True)
    patient_blood_type = models.CharField(max_length=10,choices = blood_type)  
    patient_condtion = models.CharField(max_length=100,default='')
    patient_assignednurse = models.ForeignKey(User,default=0,on_delete=models.CASCADE, db_constraint=False)
    patient_date_added = models.DateTimeField(default=datetime.today)


    def __str__(self):
        return self.patient_name

    
    def get_absolute_url(self):       
        return reverse('patient-detail', kwargs={'pk': self.pk})

    # def save(self, *args, **kwargs):
    #     r = User.objects.get(id=self.patient_assignednurse.id)
    #     if r: 
                            
    #         subject = "New patient - Neo Natal"   
    #         message = " A new Patient has been assigned to you."	
    #         recipient_list = [r.email,]
    #         send_mail(subject,message,EMAIL_HOST_USER,recipient_list,fail_silently = False)
    #         print(r.email)
    #         return super().save(*args, **kwargs)

class medical_record(models.Model):
    hiv_status=(
        ("Negative","Negative "),
        ("Positive","Posetive"),
  
    )
    drug_use=(
        ("Yes","Yes"),
        ("No","No"),
  
    )
    userid = models.ForeignKey(User,on_delete=models.CASCADE)
    patientid = models.ForeignKey(patient,on_delete = models.CASCADE)
    bptop= models.IntegerField(default='',validators=[MaxValueValidator(160),MinValueValidator(90)])
    bpbottom= models.IntegerField(default='',validators=[MaxValueValidator(100),MinValueValidator(50)])
    hbc = models.IntegerField(default='',validators=[MaxValueValidator(18),MinValueValidator(1)])#hemoglobin count
    usedrugs = models.CharField(max_length=100,choices=drug_use)
    hiv = models.CharField(max_length=100,choices = hiv_status)
    weight = models.DecimalField(max_digits=5,decimal_places=2,validators=[MinValueValidator(0)])
    height = models.DecimalField(max_digits=5,decimal_places=2,validators=[MinValueValidator(0)])
    bmi = models.DecimalField(max_digits=5,default='',decimal_places=2)


    def __str__(self):
        return self.patientid.patient_name

    def get_absolute_url(self):
        return reverse('patient-detail',kwargs={'pk':self.patientid.id})

patients/views.py
from django.views.generic import (ListView,DetailView,UpdateView ,DeleteView,CreateView)
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from neonatal.settings import EMAIL_HOST_USER
from django.shortcuts import render,redirect
from .models import patient ,medical_record
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.db.models import Q 
from django.core.mail import send_mail
from django.http import HttpResponse
from django.contrib import messages
from main.forms import *


import io
import csv
import reportlab
from reportlab.pdfgen import canvas
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from django.http import FileResponse
from reportlab.lib.pagesizes import letter



# Create your views here.


class patientslistview(LoginRequiredMixin , ListView):
    model = patient
    template_name = 'patients/patientslist.html'
    context_object_name = 'patients'
    paginate_by =  10
    

    def get_context_data(self, **kwargs):
        context = super(patientslistview,self).get_context_data(**kwargs)
        #context['patients'] = patient.objects.all()
        context['assignednurse'] = User.objects.all()
        return context


class patientdetail(LoginRequiredMixin, DetailView):
    model= patient
    template_name =  'patients/patientdetail.html'
    context_object_name = 'patientdetail'

    def get_context_data(self,**kwargs):
        context = super(patientdetail, self).get_context_data(**kwargs)
        context['medical_record'] = medical_record.objects.filter(patientid=self.kwargs['pk'])
        context['qs'] = User.objects.all()
        #context['hbccount'] = medical_record.objects.values('hbc').annotate(count=Count('hbc'))
        context['bmicount'] = medical_record.objects.filter(Q(patientid = self.kwargs['pk']) & Q(bmi__lte=18) ).count()
        context['numberofchildren'] = child.objects.filter(motherid_id = self.kwargs['pk']).count()
        context['hbccount'] = medical_record.objects.filter(patientid = self.kwargs['pk']).count()
        context['normalhbc'] = medical_record.objects.filter(Q(patientid = self.kwargs['pk']) & Q( hbc__gte=11)).count()
        context['notnormalhbc'] = medical_record.objects.filter(Q(patientid = self.kwargs['pk']) & Q( hbc__lte=11)).count()
        if context['hbccount'] == 0 :
            return context
        context['survival'] = ((context['normalhbc'] / context['hbccount']) * 100)
        context['nochancesurvival'] = ((context['notnormalhbc'] / context['hbccount']) * 100)
        return context


class AddPatientView(LoginRequiredMixin , SuccessMessageMixin,CreateView):
    model = patient
    form_class = AddPatientForm
    template_name = 'patients/addpatients.html'
    success_url = reverse_lazy('patients')
    success_message = 'Patient successfully Added'

class AddMedcialRecordView(LoginRequiredMixin ,SuccessMessageMixin,CreateView):

    model = medical_record
    form_class = AddMedicalRecordForm
    template_name = 'patients/addmedicalrecord.html'
    success_message = 'Patient Medical Record successfully Added'


    def get_context_data(self, **kwargs):
        context= super(AddMedcialRecordView,self).get_context_data(**kwargs)
        context['pname'] = patient.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self,form):
        patientidd = patient.objects.get(id=self.kwargs['pk'])    
        form.instance.patientid = patientidd
        form.instance.userid = self.request.user #adding the logged in user to the from instance
        #a = medical_record.objects.get(Patientid=self.kwargs['pk'])
        return super().form_valid(form)


class ViewChildrenView(LoginRequiredMixin,DetailView):
    model = patient
    template_name = 'patients/patientchildren.html'
    context_object_name = 'children'


    def get_context_data(self,**kwargs):
        context  = super(ViewChildrenView, self).get_context_data(**kwargs)
        context['children'] = child.objects.filter(motherid = self.kwargs['pk'])
        context['mother'] = child.objects.filter(motherid = self.kwargs['pk']).distinct()
        return context

class DeletePatientView(LoginRequiredMixin,SuccessMessageMixin,DeleteView):
    model = patient
    success_url = reverse_lazy('patients')
    success_message = "Patient SuccessFully Deleted"

class UpdatepatientView(LoginRequiredMixin,SuccessMessageMixin,UpdateView):
    model = patient
    form_class = AddPatientForm
    template_name = 'patients/addpatients.html'
    success_url = reverse_lazy('patients')
    success_message = "Patient details SuccessFully Updated"

@login_required
def assignurset(request,pk):
    patientobj = patient.objects.get(id=pk)
    assignednurse = User.objects.all()
    return render(request,'patients/assignurset.html',{
        'patientobj':patientobj,
        'assignednurse':assignednurse
        })

@login_required
def AssignNurseView(request,pk):

    protocol = 'http://'	
    host = request.get_host()
    post = patient.objects.get(id=pk)
    r = User.objects.get(id=request.POST['nurseid'])
    if request.method == 'POST':
             
        
        post.patient_assignednurse = r
        post.save()
        subject = "New patient - Neo Natal"
        link = protocol + host + reverse('patient-detail',kwargs={'pk':post.id})
        message = " A new Patient has been assigned to you. Login to view "	+ link
        recipient_list = [r.email,]
        send_mail(subject,message,EMAIL_HOST_USER,recipient_list,fail_silently = False)
        messages.success(request,f'Patient { post.patient_surname } { post.patient_name }has been Assinged to a Nurse')
        return redirect('patients')
        
@login_required
def delete_medical_record(request,pk):
    patientmedcicalrecord = medical_record.objects.get(pk=pk)
    patientmedcicalrecord.delete()
    messages.success(request,f' record deleted')
    return HttpResponse('')

def export_pdf(request):

    buf = io.BytesIO()
    c = canvas.Canvas(buf,pagesize=letter,bottomup=0)
    textob = c.beginText()
	#textob.setTextOrigin(inch,inch)
    textob.setFont("Helvetica",14)
    objpatients = patient.objects.all()
    row = []
    for objb in objpatients:
        row.append(objb.patient_name)
        row.append(objb.patient_surname)
        row.append(objb.patient_assignednurse)
        row.append(objb.patient_date_added)
    for line in row:
        textob.textLine(line)
        c.drawText(textob)
        c.showPage()
        c.save()	
        buf.seek(0)
        return FileResponse(buf, as_attachment=True, filename='patients.pdf')


def export_csv(request):
    
	response = HttpResponse(content_type='text/csv')
	response['Content-Disposition']=  'attachment; filename=patients.csv'
	writer =csv.writer(response)
	writer.writerow(['Patient Name','Patient Surname','Assigned nurse'])
	objpatient = patient.objects.all()


	for obj in objpatient:
		writer.writerow([obj.patient_name,obj.patient_surname,obj.patient_assignednurse]),
	return response
    

patients/templates/patients/addmedicalrecord.html
{% extends "main/header.html "%}
{% load static  %}
{% load crispy_forms_tags %}
{% block content%}
 

<br>
  
<h3>Adding Medical record for  <br>{{  pname.patient_name }}  {{  pname.patient_surname }} </h3>

 <form method="POST" enctype="multipart/form-data" autocomplete="off">
       {% csrf_token %}
     <div class="container">
  <div class="row">
    <div class="col">
      {{ form|crispy }}

    

      <button type="submit" class="btn btn-info">
        Submit
       
       </button>
    </div>
    <div class="col">
    
    
    </div>
  
  </div>
</div>
<hr/>
<script src="{% static 'main/js/jquery.js' %}"></script>  



<script>
  $("input").on("input", function() {
    var ret = parseInt($("#id_weight").val()) / parseInt($("#id_height").val() * 2 )
    $("#id_bmi").val(ret.toFixed(2));
  });

  
 
  
</script>
    {% endblock content %}

patients/templates/patients/addpatients.html
{% extends "main/header.html "%}
{% load static  %}
{% load crispy_forms_tags %}
{% block content%}
 
<br/>
{{ form.errors }}
{% if object.patient_name %}
  
<h3>Update  Patient details </h3>
{% include 'main/messages.html' %}
{% else %}

<h3>Add New Patient</h3>

{% endif %}
  


 <form method="POST" enctype="multipart/form-data" autocomplete="off">
       {% csrf_token %}
     <div class="container">
  <div class="row">
    <div class="col">
      {{ form.patient_name|as_crispy_field }}

      {{ form.patient_surname|as_crispy_field }}

      {{ form.patient_nid|as_crispy_field }}

      
    </div>
    <div class="col">
      {{ form.patient_blood_type|as_crispy_field }}

      {{ form.patient_condtion|as_crispy_field }}
      

      {{ form.patient_assignednurse|as_crispy_field }}
      <button  type="submit" class="btn btn-success">
      
      Submit
     
     </button>
    </div>
  
  </div>
</div>
<hr/>

    {% endblock content %}

  

patients/templates/patients/assignurset.html
{% extends "main/header.html "%}
{% load static  %}
{% block content%}
<br/><br/>

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-sm-6">
            <h3>Assigning Nurse to  {{   patientobj.patient_name}}  {{  patientobj.patient_surname}} </h3>
            <br/>
            <form  method="Post" action="{% url 'assign-nurse' patientobj.id %}" >
             {% csrf_token %}
       
            <select name="nurseid" class="form-control" id="">
             {% for a in assignednurse %}
             <option value="{{ a.pk }}">{{ a.last_name }} </option>
             {% endfor %}
            
            </select>                          
           
        </div>
       
       
    </div>
</div>
<button type="submit" class="btn btn-success">Assign</button>
</form>

<button class="btn btn-primary"  data-dismiss="modal"><a href="{% url 'patients' %}">Cancel</a></button>
{% endblock %}

patients/templates/patients/patient_confirm_delete.html
{% extends "main/header.html "%}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}


<div class="container">

  

    <form method="POST">
        {% csrf_token %}
<fieldset class="form-group">
 <div class="col-xs-6">
    <h4>You are Deleting   {{  object.patient_name }} {{ object.patient_surname}}'s  </h4>

    <h3>Are You Sure</h3>
       <div class="form-group">
  <button type="submit" class="btn btn-danger">Yes Delete</button>
   <a href="{% url 'patients'%}" class="btn btn-warning">No Cancel</a>
       </div>
       </fieldset>
    
 </div>
    
    </form>
  </div>
</div>

  
{% endblock content %}

patients/templates/patients/patientchildren.html
{% extends "main/header.html "%}
{% load static  %}
{% block content%}


<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
    <h2 class="h3">
     


    
{{ object.patient_name }} {{ object.patient_surname }}

    

   </h2>


  </div>
  {% include "main/messages.html" %}


  <form class="form-inline my-6 my-lg-6" method="Post"  action="{%  url 'searched-child' %}">
    {% csrf_token %}
     <input class="form-control mr-sm-2" name="searchedchild" required="required" type="text" placeholder="Search" aria-label="Search">
     <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
   
   </form>

<table class="table table-hover">
<thead class="thead-dark">

<tr>
   <th scope="col">Child id</th>

 <th scope="col">D.O.B</th> 
 <th scope="col">Action</th>
</tr>
</thead>
<tbody>
{% for child in children %}
<tr>
<th scope="row">{{  child.childregno}}    {{  child.motherid.patient_name}}</th>
   <th scope="row"> {{ child.Dob|date:"d M Y" }}</th> 

 
  
  <td><div class="btn-group dropleft">
<button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
Action
</button>
<div class="dropdown-menu" aria-labelledby="dropdownMenuButton">

<a class="dropdown-item" href="{% url 'child-detail' child.id %}">View</a>



</div>
</div></td>
</tr>

</tbody>

{% endfor %}
</table>
{% endblock content%}

patients/templates/patients/patientdetail.html
{% extends "main/header.html "%}
{% load static  %}
{% block content%}
<script src="{% static 'main/js/chartt.js' %}"></script>
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        {% if patientdetail %}
        <h2 class="h2"> {{ object.patient_name|capfirst }} {{  object.patient_surname }}</h2>
  {% endif %}
        <div class="btn-toolbar mb-4 mb-md-0">
          <div class="btn-group mr-2">
            
            <a href="{% url 'add-medical-record' object.id %}"><button type="button"  class="btn btn-sm btn-outline-primary">Add Medical Record</button></a>
          </div>
          {% if survival  %}
          <div class="btn-group mr-2">
            <a href="{% url 'add-child' object.id %}"><button type="button" class="btn btn-sm btn-outline-primary">Add Child</button></a>
            
         </div>
            <div class="btn-group mr-2">
          
            <a href="{%url 'view-children' object.id %}"><button type="button" class="btn btn-sm btn-outline-primary">View Children</button></a>
     </div>
     {% else %}
    
     {% endif  %}
        </div>
      </div>



      {% include "main/messages.html" %}
      <hr>
	
        

   <div class="container">
 
      <h5 class="card-title">{{object.patient_name}}  {{object.patient_surname}} | </h5>
      Total Number Of Children = {{ numberofchildren }}
   
 
   
    <hr>
  <div class="row">
    <div class="col">
<div class="card" style="width: 20rem;">

<img src="" />
  <div class="card-body">
 


   
    <canvas id="mylineChart" width="10" height="10"></canvas>
  </div>
</div>

  </div>
  <div class="card" style="width: 20rem;">
 
    <canvas id="myPieChart" width="10" height="10"></canvas>
  
  </div>
   <div class="col">


<hr>

{{ survival }} / {{ nochancesurvival }}<br/>
{% if survival  %}
  


The baby has a {{ survival|floatformat:0 }}% chance of surviving becacause of better full blood count

<hr>
The baby has a {{ nochancesurvival|floatformat:0 }}% chance of not surviving becacause of bad full blood count
{% else %}


no data
{% endif %}   
<hr>

<!-- {{ bmicount }} -->


  
   
    </div>
     </div>
</div>

<canvas id="myChart" width="400" height="150"></canvas>  
<table class="table table-hover">
  <thead class="thead-light">

    <tr>
    
      <th scope="col">Hypertension(BP)</th>
      <th scope="col">FBC</th>
       <th scope="col">USe Drugs?</th>
       <th scope="col">HIV</th>
      <th scope="col">Weight</th>
      <th scope="col">Height</th>
      <th scope="col">BMI</th>
       <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
 
    
   
    
    <!-- pmr = patient_medical_record -->
    {% for pmr in medical_record %}
    <tr hx-target="this" hx-swap="outerHTML">
     
      <td>{{ pmr.bptop }}/{{ pmr.bpbottom }}</td>
      <td>{{ pmr.hbc }}</td>
      <td>{{ pmr.usedrugs }}</td>
      <td>{{ pmr.hiv  }}</td>
      <td>{{ pmr.weight  }}</td>
      <td>{{ pmr.height }}</td>

      {% if pmr.bmi < 18 %}
      <td style="background-color: orange;color:white">{{ pmr.bmi  }}</td>
      {% elif pmr.bmi > 18 and pmr.bmi <= 25  %}
      <td style="background-color: green;color:white;">{{ pmr.bmi  }}</td>
      {% else %}
      <td style="background-color: red;color:white;">{{ pmr.bmi  }}</td>
      {% endif %}
      <td> 

        <button hx-post="{%  url 'delete-medical-record' pmr.id %}">Delete</button>
      </td>
    </tr>
    {% endfor %}
  </tbody>
  </table>
  <script>
    document.body.addEventListener('htmx:configRequest', (event) => {
      event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
    })
  </script>
  
<script>
  var xValues = [1,2,3,4,5,6,8,9];

new Chart("myChart", {
  type: "bar",
  data: {
    labels: xValues,
    datasets: [
  {
      label:'Systolic',
      data: [

              {% for entry in medical_record %}
              {{ entry.bptop }}
              {% if not forloop.last %},
              {% endif %}
              {% endfor %}
],
backgroundColor: [
              'rgba(255, 206, 86, 0.2)'
            
              
            ],
            borderColor: [
               
                'rgba(255, 199, 64, 1)'
            ],
            borderWidth: 5
     // borderColor: "blue",
     // fill: false
    },
{
    label:'Diastolic',
      data: [
  
              {% for entry in medical_record %}
              {{ entry.bpbottom }}
              {% if not forloop.last %},
              {% endif %}
              {% endfor %}

],
backgroundColor: [
          'rgba(75, 192, 192, 0.2)',
            
              
            ],
            borderColor: [
               
   
            ],
            borderWidth: 5

    },{
      label:'Full blood Count',
      data: [
              {% for entry in medical_record %}
              {{ entry.hbc }}
              {% if not forloop.last %},
              {% endif %}
              {% endfor %}
],
backgroundColor: [
          'rgba(255, 255, 255, 0.2)',
            
              
            ],
borderColor: [
               
               'rgba(255, 0, 0, 1)'
           ],
                borderWidth: 5
    },{
    label:'Bmi',
      data: [
              {% for entry in medical_record %}
              {{ entry.bmi }}
              {% if not forloop.last %},
              {% endif %}
              {% endfor %}
],
     backgroundColor: [
          'rgba(255, 255, 255, 0.2)',
            
              
            ],
borderColor: [
               
               'rgba(0, 127, 255, 1)'
           ],
            borderWidth: 5
}



]
  },
  options: {
    legend: {display: false}
  }
});
</script>
<script>
  const ctxpie = document.getElementById('myPieChart').getContext('2d');
  const myPieChart = new Chart(ctxpie, {
      type: "pie",
      data: {
          labels: [
            'survival'  , 'not surviving'
          ],
          datasets: [{
              label: '',
              data: [
                
           {{ survival }}, {{ nochancesurvival }}
              
               
              
              ],
              
         backgroundColor: [
                  'rgba(0, 200, 5,0.5)',
                  'rgba(255, 0, 1,0.5)',
                
                  
              ],
              borderColor: [
                  'rgba(255, 255, 255 , 1)',
                 
                
              ],
              borderWidth: 1
          }]
      },
    
  });
  </script>
  
  <script>
    const ctxline = document.getElementById('mylineChart').getContext('2d');
    const mylineChart = new Chart(ctxline, {
        type: "line",
        data: {
            labels: [ 1 ,2 ,3 ,4 ,5 , 6 ,7 ,8 , 9
         
            ],
            datasets: [{
                label: [
                  
              'BMI recordings'
              
              ],
                data: [
                  
              {% for pmr in medical_record %}
              {{ pmr.bmi }}
              {% if not forloop.last %},
              {% endif %}
              {% endfor %}
                
                 
                
                ],
                
           backgroundColor: [
                    'rgba(0, 200, 5,0.5)',
                 
                  
                    
                ],
                borderColor: [
                    'rgba(0, 09, 0, 1)',
                   
                  
                ],
                borderWidth: 1
            }]
        },
      
    });
    </script>
<br>
{% endblock %}





    
  
   
 

patients/templates/patients/patientlistbp.html
{% extends "main/header.html "%}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
 <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
        <h2 class="h3">All Patients

         
       </h2>

        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{% url 'add-patient' %}">Add Patient</a></button>
            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>
      {% include "main/messages.html" %}
 <!-- <form class="form-inline my-4 my-lg-2" method="Post"  action="  url 'searched-books' " >
     {% csrf_token %}
      <input class="form-control mr-sm-2" name="searchedbook" required="required" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    
    </form> -->



<table class="table table-hover">
  <thead class="thead-dark">

    <tr>
       <th scope="col">id</th>
      <th scope="col">name</th>
      <th scope="col">surname</th>
      <th scope="col">Assigend nurse</th>
   
       <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    {% for patient  in patients %}
    <tr>
       <th scope="row">{{  patient.id}}</th>
      <th scope="row">{{  patient.patient_name}}</th>
      <th scope="row">{{  patient.patient_surname}}</th>
      <th scope="row">{{  patient.patient_assignednurse.first_name.0}} - {{  patient.patient_assignednurse.last_name|capfirst}}</th>

     
      
      <td><div class="btn-group dropleft">
  <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
   Action
  </button>
  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
    <a class="dropdown-item" href="{% url 'add-medical-record' patient.id %}">Create MR</a>
    <a class="dropdown-item" href="{% url 'patient-detail' patient.id %}">View</a>
    <a class="dropdown-item" href="{% url 'patient-update' patient.id %}">Update</a>
    <a class="dropdown-item" href="{% url 'delete-patient' patient.id  %}">Delete</a>
    <a class="dropdown-item" href="{% url 'assignurset' patient.id %}"   >Assign Nurse </a>
   
  </div>
</div></td>
    </tr>
    
  </tbody>
  
  {% endfor %}
</table>
 <nav aria-label="Page navigation example">
  <nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
{% if is_paginated %}

      {% if page_obj.has_previous %}
       <li class="page-item disabled"> <a class="btn btn-outline-secondary mb-4"  href="?page=1">First </a></li>
       <li class="page-item disabled"> <a class="btn btn-outline-secondary mb-4"  href="?page={{ page_obj.previous_page_number}}">Previous </a></li>
      {% endif %}

      {%  for num in page_obj.paginator.page_range  %}

        {% if page_obj.number == num %}

        <li class="page-item disabled">  <a class="btn btn-outline-info mb-4"  href="?page={{ num }}">{{ num }} </a></li>

        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}

            <li class="page-item disabled"> <a class="btn btn-outline-info mb-4"  href="?page={{ num }}">{{ num }} </a></li>
         {% endif %}

        {% endfor%}

  {% if page_obj.has_next %}
     <li class="page-item disabled">   <a class="btn btn-outline-info mb-4"  href="?page={{ page_obj.next_page_number }}">Next </a></li>
         <li class="page-item disabled">   <a class="btn btn-outline-info mb-4"  href="?page={{ page_obj.paginator.num_pages }}">Last </a></li>
      {% endif %}
      {% endif %}


  
  </ul>
</nav>






{%endblock content%}
   



    